### ISSUE TITLE
每次重新执行yarn start和yarn run android后都会报错 ，需要执行gradlew clean才会正常

### ISSUE THREAD

**Issue by heqs** [duheng/Mozi#40]
报错内容如下
Error: EPERM: operation not permitted, lstat 'G:\MySource\noter\Mozi\android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values'
Emitted 'error' event at:
    at NodeWatcher.<anonymous> (G:\MySource\noter\Mozi\node_modules\sane\src\node_watcher.js:289:14)
    at G:\MySource\noter\Mozi\node_modules\graceful-fs\polyfills.js:284:29
    at FSReqWrap.oncomplete (fs.js:154:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

然后执行 gradlew clean，重新yarn start和yarn run android就 正常了，不知道为什么会这样

**Comment by duheng** [comment]
> 报错内容如下
> Error: EPERM: operation not permitted, lstat 'G:\MySource\noter\Mozi\android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values'
> Emitted 'error' event at:
> at NodeWatcher. (G:\MySource\noter\Mozi\node_modules\sane\src\node_watcher.js:289:14)
> at G:\MySource\noter\Mozi\node_modules\graceful-fs\polyfills.js:284:29
> at FSReqWrap.oncomplete (fs.js:154:21)
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> 
> 然后执行 gradlew clean，重新yarn start和yarn run android就 正常了，不知道为什么会这样

你用的是Android Studio3.+ ？

**Comment by heqs** [comment]
我的as版本是3.5.3，貌似只要在命令行执行yarn start和yarn run android吧，需要用到as吗？

**Comment by duheng** [comment]
> 我的as版本是3.5.3，貌似只要在命令行执行yarn start和yarn run android吧，需要用到as吗？

这个是模拟器的问题，每次升级Android Studio都会遇到类似问题, 目前你先用安卓机调试开发，我后面有空兼容一下。

**Comment by heqs** [comment]
好的，谢谢大佬
